### ISSUE TITLE
SBOM missing main component

### ISSUE THREAD

**Issue by malice00** [CycloneDX/cyclonedx-cocoapods#74]
As I had requested in #58, there was no dependency information in the SBOM, so Dependeny-Track didn't show a graph. Unfortunately, I haven't been able to follow up on this for quite some time, but now that I finally got around to it, I noticed that DT is still not showing a graph.
From my investigation, I think this is because DT needs a 'main' component under `bom/metadata/component` and the list of its dependencies just like in #58.

**Comment by macblazer** [comment]
The `bom/metadata/component` is only generated if the component's name, version, and type are provided using the `--name`, `--version`, and `--type` parameters.

Currently that `bom/metadata/component` is not listed in the `dependencies` section because the rest of the bom **is** the dependencies of the metadata component.  But maybe the `bom/metadata/component` is supposed to be listed in the dependencies section as the top level thing and linked to everything else.  I'll check in with the CycloneDX maintainers group and gather some more info on this topic.

**Comment by malice00** [comment]
Ah, that's what does parameters do! That actually fixed the missing component, however the dependency-graph is still empty. From what I've seen eg in cdxgen, what's missing is the references from this main component to it's direct dependencies. No need to add the component again.

**Comment by macblazer** [comment]
I believe PR #70 fixed this problem, but there was never an official release of that code.

I've been working on some cleanup and additional functionality (#71 and #69).  Once I've gotten those things finished off, I'll do an official release which should get the fix out there.

**Comment by macblazer** [comment]
Version 1.4.0 has been released on RubyGems.org.  Give it a try!  Hopefully the graph will show up in Dependency Track.

The example_bom.xml file now shows the [top level dependencies](https://github.com/CycloneDX/cyclonedx-cocoapods/blob/e11d412df1d53b99f45cfb460df269411d699ae2/example_bom.xml#L168-L172).

**Comment by malice00** [comment]
Thanks, that did it! The dependency-graph is now showing.
